// This file was auto-generated by ML.NET Model Builder. 

using System;
using PredictorML.Model;

namespace PredictorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Year = 2010F,
                Quarter = 1F,
                Pop_density = 142.9F,
                Men_quan = 65.734F,
                Women_quan = 77.166F,
                Rate_unemp = 3.061938F,
                Psych_clinic = 1232F,
                Drug_clinic = 1074F,
                Family_incom = 0.22F,
                Child_homeless = 0.0032F,
                Quan_conviction = 0.014F,
                Quan_education = 0.361F,
                Cof_crime = 0.13F,
                Quan_migrant = 254089F,
                Quan_gun = 252F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Crime_count with predicted Crime_count from sample data...\n\n");
            Console.WriteLine($"Year: {sampleData.Year}");
            Console.WriteLine($"Quarter: {sampleData.Quarter}");
            Console.WriteLine($"Pop_density: {sampleData.Pop_density}");
            Console.WriteLine($"Men_quan: {sampleData.Men_quan}");
            Console.WriteLine($"Women_quan: {sampleData.Women_quan}");
            Console.WriteLine($"Rate_unemp: {sampleData.Rate_unemp}");
            Console.WriteLine($"Psych_clinic: {sampleData.Psych_clinic}");
            Console.WriteLine($"Drug_clinic: {sampleData.Drug_clinic}");
            Console.WriteLine($"Family_incom: {sampleData.Family_incom}");
            Console.WriteLine($"Child_homeless: {sampleData.Child_homeless}");
            Console.WriteLine($"Quan_conviction: {sampleData.Quan_conviction}");
            Console.WriteLine($"Quan_education: {sampleData.Quan_education}");
            Console.WriteLine($"Cof_crime: {sampleData.Cof_crime}");
            Console.WriteLine($"Quan_migrant: {sampleData.Quan_migrant}");
            Console.WriteLine($"Quan_gun: {sampleData.Quan_gun}");
            Console.WriteLine($"\n\nPredicted Crime_count: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
